AllCops:
  Exclude:
    - './Gemfile'
    - './bin/bundle'
    - ./db/**/*
    - ./node_modules/**/*
    - ./config/**/*

Style/FrozenStringLiteralComment:
  Enabled: false

Style/StringLiterals:
  EnforcedStyle: double_quotes

Style/Documentation:
  Enabled: false

Metrics/AbcSize:
  Enabled: false

Style/FormatStringToken:
  Enabled: false
#Metrics/LineLength:
#  Max: 15